chore: setup shellspec for testing bash scripts

diff --git a/bin/gh-create-pr b/bin/gh-create-pr
--- a/bin/gh-create-pr
+++ b/bin/gh-create-pr
@@ -42,12 +42,12 @@ title=${title:-"Add/Expire partitions"}
 commit_msg=${commit_msg:-"${title}"}
 
 if git diff --quiet -- && [ -z "$(git ls-files --others --exclude-standard)" ]; then
-    echo "✅ No changes detected. Exiting..."
+    echo "INFO: No changes detected. Exiting..."
     exit 0
 fi
 
 if ! gh auth status &>/dev/null; then
-    echo "❌ GitHub CLI is not authenticated. Run 'gh auth login'."
+    echo "ERROR: ❌ GitHub CLI is not authenticated. Run 'gh auth login'." >&2
     exit 1
 fi
 
@@ -68,10 +68,10 @@ git push origin "${full_branch}" --force
 
 PR_URL="$(gh pr list --head "${full_branch}" --state open --json url --jq .[].url)"
 if [[ -n "${PR_URL}" ]]; then
-    echo "PR already exists -> ${PR_URL}. Exiting..."
+    echo "INFO: PR already exists -> ${PR_URL}. Exiting..."
     exit 0
 else
-    echo "Creating PR"
+    echo "INFO: Creating PR"
     gh pr create --base "${base_branch}" \
         --head "${full_branch}" \
         --title "${title}" \
