feat: move test data seeding into initdr

diff --git a/src/bin/pg-start b/src/bin/pg-start
--- a/src/bin/pg-start
+++ b/src/bin/pg-start
@@ -46,7 +46,7 @@ if [[ -z "${pg_major_version}" ]]; then
 fi
 
 if (( pg_major_version < 13 )); then
-  echo "Error: PostgreSQL major version must be at least 13"
+  echo "Error: PostgreSQL major version must be at least 13" >&2
   exit 1
 fi
 
@@ -57,6 +57,10 @@ if [[ -z ${NO_CLUSTER+yes} ]]; then
     echo "INFO: Creating PostgreSQL cluster"
     pg_createcluster --start "${pg_major_version}" pgpartium -- -A trust
     # Apply init directory if provided and exists
+    # if [[ -d "${init_dir}" ]]; then
+    #     echo "INFO: Applying init scripts from ${init_dir}"
+    # fi
+
     if [[ -d "${init_dir}" ]]; then
         echo "INFO: Applying init scripts from ${init_dir}"
 
@@ -76,6 +80,7 @@ if [[ -z ${NO_CLUSTER+yes} ]]; then
                     psql --username=postgres \
                         --dbname=postgres \
                         -v "ON_ERROR_STOP=1" \
+                        --quiet \
                         --no-psqlrc -f "${file}"
                     ;;
                 *.sql.gz)
@@ -83,6 +88,7 @@ if [[ -z ${NO_CLUSTER+yes} ]]; then
                     psql --username=postgres \
                         --dbname=postgres \
                         -v "ON_ERROR_STOP=1" \
+                        --quiet \
                         --no-psqlrc
                     ;;
             esac
diff --git a/src/bin/pgp-expire-partitions b/src/bin/pgp-expire-partitions
--- a/src/bin/pgp-expire-partitions
+++ b/src/bin/pgp-expire-partitions
@@ -189,9 +189,9 @@ EOF
 done < <(yq '.generates.tables[] | @json' "${config}")
 
 if [ ${#failed_tables[@]} -gt 0 ]; then
-    echo "ERROR: failed for ${#failed_tables[@]} table(s):" 2>&1
+    echo "ERROR: failed for ${#failed_tables[@]} table(s):" >&2
     for table in "${!failed_tables[@]}"; do
-        echo "  '${table}': ${failed_tables[${table}]}" 2>&1
+        echo "  '${table}': ${failed_tables[${table}]}" >&2
     done
     exit 1
 else
