feat: checkpoint

diff --git a/src/bin/pgp-make-partitions b/src/bin/pgp-make-partitions
--- a/src/bin/pgp-make-partitions
+++ b/src/bin/pgp-make-partitions
@@ -49,6 +49,8 @@ while getopts "c:u:w:s:p:d:h" option; do
 done
 
 set -euo pipefail
+IFS=$'\n\t'
+# set -x
 
 config=${config:-}
 dbuser=${dbuser:-postgres}
@@ -56,6 +58,9 @@ dbpassword=${dbpassword:-postgres}
 dbhost=${dbhost:-localhost}
 dbport=${dbport:-5432}
 dbname=${dbname:-postgres}
+
+# shellcheck source=../utils/logging.sh
+# source ../utils/logging.sh
 
 # Ensure config is provided.
 if [[ -z "${config}" ]]; then
@@ -67,7 +72,7 @@ fi
 jsonschema /src/schema.json <<< "$(yq -o=json "${config}")"
 
 # Set defaults.
-export DEFAULT_TABLESPACE="pg_default"
+export DEFAULT_TABLESPACE=NULL
 export DEFAULT_PAST=0
 export DEFAULT_FUTURE=0
 export DEFAULT_RETENTION=NULL
@@ -78,35 +83,37 @@ export DEFAULT_STORAGE_PARAMETERS="{}"
 export DEFAULT_TIMEZONE="Etc/UTC"
 
 # Extract global configs.
-GLOBAL_PARTITION_SCHEMA=$(yq '.generates.partition_schema' "${config}")
-GLOBAL_PARTITION_NAME_TEMPLATE=$(yq '.generates.name_template' "${config}")
-GLOBAL_PAST=$(yq '.generates.past // strenv(DEFAULT_PAST)' "${config}")
-GLOBAL_FUTURE=$(yq '.generates.future // strenv(DEFAULT_FUTURE)' "${config}")
-GLOBAL_INTERVAL=$(yq '.generates.interval' "${config}")
-GLOBAL_RETENTION=$(yq '.generates.retention // strenv(DEFAULT_RETENTION)' "${config}")
-GLOBAL_CREATE_DEFAULT=$(yq '.generates.create_default // strenv(DEFAULT_CREATE_DEFAULT)' "${config}")
-GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE=$(yq '.generates.default_partition_name_template' "${config}")
-GLOBAL_SKIP_OVERLAPPING=$(yq '.generates.skip_overlapping // strenv(DEFAULT_SKIP_OVERLAPPING)' "${config}")
-GLOBAL_IDEMPOTENT_DDL=$(yq '.generates.idempotent_ddl // strenv(DEFAULT_IDEMPOTENT_DDL)' "${config}")
-GLOBAL_PARTITION_TABLESPACE=$(yq '.generates.partition_tablespace // strenv(DEFAULT_TABLESPACE)' "${config}")
-GLOBAL_STORAGE_PARAMETERS=$(yq -o=json '.generates.partition_storage_parameters // (strenv(DEFAULT_STORAGE_PARAMETERS) | fromjson)' "${config}")
-GLOBAL_TIMEZONE=$(yq '.generates.timezone // strenv(DEFAULT_TIMEZONE)' "${config}")
+GLOBAL_PARTITION_SCHEMA="$(yq '.generates.partition_schema' "${config}")"
+GLOBAL_PARTITION_NAME_TEMPLATE="$(yq '.generates.name_template' "${config}")"
+GLOBAL_PAST="$(yq '.generates.past // strenv(DEFAULT_PAST)' "${config}")"
+GLOBAL_FUTURE="$(yq '.generates.future // strenv(DEFAULT_FUTURE)' "${config}")"
+GLOBAL_INTERVAL="$(yq '.generates.interval' "${config}")"
+GLOBAL_RETENTION="$(yq '.generates.retention // strenv(DEFAULT_RETENTION)' "${config}")"
+GLOBAL_CREATE_DEFAULT="$(yq '.generates.create_default // strenv(DEFAULT_CREATE_DEFAULT)' "${config}")"
+GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE="$(yq '.generates.default_partition_name_template' "${config}")"
+GLOBAL_SKIP_OVERLAPPING="$(yq '.generates.skip_overlapping // strenv(DEFAULT_SKIP_OVERLAPPING)' "${config}")"
+GLOBAL_IDEMPOTENT_DDL="$(yq '.generates.idempotent_ddl // strenv(DEFAULT_IDEMPOTENT_DDL)' "${config}")"
+GLOBAL_PARTITION_TABLESPACE="$(yq '.generates.partition_tablespace // strenv(DEFAULT_TABLESPACE)' "${config}")"
+GLOBAL_INDEX_TABLESPACE="$(yq '.generates.index_tablespace // strenv(DEFAULT_TABLESPACE)' "${config}")"
 
-export GLOBAL_PARTITION_TABLESPACE GLOBAL_PARTITION_SCHEMA GLOBAL_PARTITION_NAME_TEMPLATE GLOBAL_PAST \
+GLOBAL_STORAGE_PARAMETERS="$(yq -o=json '.generates.partition_storage_parameters // (strenv(DEFAULT_STORAGE_PARAMETERS) | fromjson)' "${config}")"
+GLOBAL_TIMEZONE="$(yq '.generates.timezone // strenv(DEFAULT_TIMEZONE)' "${config}")"
+
+export GLOBAL_PARTITION_TABLESPACE GLOBAL_INDEX_TABLESPACE GLOBAL_PARTITION_SCHEMA \
+        GLOBAL_PARTITION_NAME_TEMPLATE GLOBAL_PAST \
     GLOBAL_FUTURE GLOBAL_INTERVAL GLOBAL_RETENTION GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE \
     GLOBAL_SKIP_OVERLAPPING GLOBAL_STORAGE_PARAMETERS GLOBAL_TIMEZONE GLOBAL_CREATE_DEFAULT GLOBAL_IDEMPOTENT_DDL
 
-GLOBAL_INDEX_TABLESPACE=$(yq '.generates.index_tablespace // strenv(GLOBAL_PARTITION_TABLESPACE)' "${config}")
 
-export GLOBAL_INDEX_TABLESPACE
+# export GLOBAL_INDEX_TABLESPACE
 
-directory=$(yq '.generates.directory' "${config}")
+directory="$(yq '.generates.directory' "${config}")"
 
 declare -A failed_tables=()
 
 # Staging area.
-temp_migration_directory=$(mktemp -d)
-temp_error_directory=$(mktemp -d)
+temp_migration_directory="$(mktemp -d)"
+temp_error_directory="$(mktemp -d)"
 
 # Stage current migrations in staging area.
 echo "INFO: Staging current migrations"
@@ -125,77 +132,77 @@ pgp-setup-infrastructure -u "${dbuser}" -w "${dbpassword}" -s "${dbhost}" -p "${
 
 # Process each partitioned table.
 while read -r table; do
-    table_schema=$(yq '.table_schema' <<< "${table}")
-    table_name=$(yq '.table_name' <<< "${table}")
-    file_name_template=$(yq '.file_name_template' <<< "${table}")
-    description=$(yq '.description.make // "Add partitions for {table_schema}_{table_name}"' <<< "${table}")
+    table_schema="$(yq '.table_schema' <<< "${table}")"
+    table_name="$(yq '.table_name' <<< "${table}")"
+    file_name_template="$(yq '.file_name_template' <<< "${table}")"
+    description="$(yq '.description.make // "Add partitions for {table_schema}_{table_name}"' <<< "${table}")"
     # Replace table_schema and table_name placeholders in the description.
     description="${description//\{table_schema\}/$table_schema}"
     description="${description//\{table_name\}/$table_name}"
 
-    output_filename=$(pgp-get-migration-filename -t "${file_name_template}" -d "${temp_migration_directory}" -m "${description}")
+    output_filename="$(pgp-get-migration-filename -t "${file_name_template}" -d "${temp_migration_directory}" -m "${description}")"
     echo "INFO: Making partitions for ${table_schema}.${table_name}"
 
-    partition_schema=$(yq '.partition.partition_schema // strenv(GLOBAL_PARTITION_SCHEMA)' <<< "${table}")
+    partition_schema="$(yq '.partition.partition_schema // strenv(GLOBAL_PARTITION_SCHEMA)' <<< "${table}")"
     # If no schema is provided either in the partition config or in the global config, default to table schema.
     if [[ "${partition_schema}" == "null" ]]; then
         partition_schema="${table_schema}"
     fi
 
-    partition_name_template=$(yq '.partition.name_template // strenv(GLOBAL_PARTITION_NAME_TEMPLATE)' <<< "${table}")
+    partition_name_template="$(yq '.partition.name_template // strenv(GLOBAL_PARTITION_NAME_TEMPLATE)' <<< "${table}")"
     if [[ "${partition_name_template}" == "null" ]]; then
         echo "ERROR: Partition name template is required." >&2
         echo "HINT: Please provide a partition name template in the config file either in the partition config or in the global config." >&2
         exit 1
     fi
 
-    partition_tablespace=$(yq '.partition.partition_tablespace // strenv(GLOBAL_PARTITION_TABLESPACE)' <<< "${table}")
-    index_tablespace=$(yq '.partition.index_tablespace // strenv(GLOBAL_INDEX_TABLESPACE)' <<< "${table}")
+    partition_tablespace="$(yq '.partition.partition_tablespace // strenv(GLOBAL_PARTITION_TABLESPACE)' <<< "${table}")"
+    index_tablespace="$(yq '.partition.index_tablespace // strenv(GLOBAL_INDEX_TABLESPACE)' <<< "${table}")"
 
-    partition_interval=$(yq '.partition.interval // strenv(GLOBAL_INTERVAL)' <<< "${table}")
+    partition_interval="$(yq '.partition.interval // strenv(GLOBAL_INTERVAL)' <<< "${table}")"
     if [[ "${partition_interval}" == "null" ]]; then
         echo "ERROR: Partition interval is required." >&2
         echo "HINT: Please provide a partition interval in the config file either in the partition config or in the global config." >&2
         exit 1
     fi
 
-    past_partitions=$(yq '.partition.past // strenv(GLOBAL_PAST)' <<< "${table}")
-    future_partitions=$(yq '.partition.future // strenv(GLOBAL_FUTURE)' <<< "${table}")
-    retention=$(yq '.partition.retention // strenv(GLOBAL_RETENTION)' <<< "${table}")
-    timezone=$(yq '.partition.timezone // strenv(GLOBAL_TIMEZONE)' <<< "${table}")
+    past_partitions="$(yq '.partition.past // strenv(GLOBAL_PAST)' <<< "${table}")"
+    future_partitions="$(yq '.partition.future // strenv(GLOBAL_FUTURE)' <<< "${table}")"
+    retention="$(yq '.partition.retention // strenv(GLOBAL_RETENTION)' <<< "${table}")"
+    timezone="$(yq '.partition.timezone // strenv(GLOBAL_TIMEZONE)' <<< "${table}")"
 
     # Because yq default value operator is used to provide alternative (or default) values
     # when a particular expression is either null or false, we cannot use it as it would
     # instead override partition level boolean values, instead we override them if they are not set.
-    skip_overlapping=$(yq '.partition.skip_overlapping' <<< "${table}")
+    skip_overlapping="$(yq '.partition.skip_overlapping' <<< "${table}")"
     if [[ "${skip_overlapping}" == "null" ]]; then
         skip_overlapping="${GLOBAL_SKIP_OVERLAPPING}"
     fi
 
-    idempotent_ddl=$(yq '.partition.idempotent_ddl' <<< "${table}")
+    idempotent_ddl="$(yq '.partition.idempotent_ddl' <<< "${table}")"
     if [[ "${idempotent_ddl}" == "null" ]]; then
         idempotent_ddl="${GLOBAL_IDEMPOTENT_DDL}"
     fi
 
-    create_default=$(yq '.partition.create_default' <<< "${table}")
+    create_default="$(yq '.partition.create_default' <<< "${table}")"
     if [[ "${create_default}" == "null" ]]; then
         create_default="${GLOBAL_CREATE_DEFAULT}"
     fi
     # If create_default is true, default_partition_name_template is required.
-    default_partition_name_template=$(yq '.partition.default_partition_name_template // strenv(GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE)' <<< "${table}")
+    default_partition_name_template="$(yq '.partition.default_partition_name_template // strenv(GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE)' <<< "${table}")"
     if [[ "${create_default}" == true && "${default_partition_name_template}" == "null" ]]; then
         echo "ERROR: Default partition name template is required when create_default is true." >&2
         echo "HINT: Please provide a default partition name template in the config file either in the partition config or in the global config." >&2
         exit 1
     fi
 
-    partition_storage_parameters=$(yq '.partition.partition_storage_parameters // strenv(GLOBAL_STORAGE_PARAMETERS)' <<< "${table}")
+    partition_storage_parameters="$(yq '.partition.partition_storage_parameters // strenv(GLOBAL_STORAGE_PARAMETERS)' <<< "${table}")"
 
-    template_table=$(yq '.template_table' <<< "${table}")
+    template_table="$(yq '.template_table' <<< "${table}")"
 
     if [[ "${template_table}" == "DEFAULT_PARTITION" ]]; then
         IFS=',' read -r template_table_schema template_table_name < <(
-            PGPASSWORD="${dbpassword}" psql --username="${dbuser}" \
+            PGUSER="${PGP_USER}" PGPASSWORD="${PGP_PASSWORD}" psql \
                 --dbname="${dbname}" \
                 --host="${dbhost}" \
                 --port="${dbport}" \
@@ -218,7 +225,7 @@ EOF
 
     elif [[ "${template_table}" == "LATEST_PARTITION" ]]; then
         IFS=',' read -r template_table_schema template_table_name < <(
-            PGPASSWORD="${dbpassword}" psql --username="${dbuser}" \
+            PGUSER="${PGP_USER}" PGPASSWORD="${PGP_PASSWORD}" psql \
                 --dbname="${dbname}" \
                 --host="${dbhost}" \
                 --port="${dbport}" \
@@ -241,7 +248,7 @@ EOF
 
     elif [[ "${template_table}" == "CURRENT_PARTITION" ]]; then
         IFS=',' read -r template_table_schema template_table_name < <(
-            PGPASSWORD="${dbpassword}" psql --username="${dbuser}" \
+            PGUSER="${PGP_USER}" PGPASSWORD="${PGP_PASSWORD}" psql \
                 --dbname="${dbname}" \
                 --host="${dbhost}" \
                 --port="${dbport}" \
@@ -263,17 +270,14 @@ EOF
         }
 
     else
-        template_table_schema=$(yq '.table_schema // ""' <<< "${template_table}")
-        template_table_name=$(yq '.table_name // ""' <<< "${template_table}")
+        template_table_schema="$(yq '.table_schema // ""' <<< "${template_table}")"
+        template_table_name="$(yq '.table_name // ""' <<< "${template_table}")"
 
     fi
 
     error_file="${temp_error_directory}/${table_schema}.${table_name}.error"
 
-    if ! PGPASSWORD="${dbpassword}" psql --username="${dbuser}" \
-        --dbname="${dbname}" \
-        --host="${dbhost}" \
-        --port="${dbport}" \
+    if ! PGUSER="${PGP_USER}" PGPASSWORD="${PGP_PASSWORD}" PGDATABASE="${PGP_DATABASE}" PGPORT="${PGP_PORT}" psql -v VERBOSITY=verbose \
         --tuples-only \
         --no-align \
         --quiet \
@@ -310,8 +314,8 @@ SELECT *
   , p_create_default=>:'create_default_partition'
   , p_default_partition_name_template=>:'default_partition_name_template'
   , p_partition_schema=>:'partition_schema'
-  , p_partition_tablespace=>:'partition_tablespace'
-  , p_index_tablespace=>:'index_tablespace'
+  , p_partition_tablespace=>NULLIF(:'partition_tablespace', 'NULL')
+  , p_index_tablespace=>NULLIF(:'index_tablespace', 'NULL')
   , p_partition_storage_parameters=>:'partition_storage_parameters'
   , p_template_table_schema=>:'template_table_schema'
   , p_template_table_name=>:'template_table_name'
@@ -339,7 +343,7 @@ EOF
 
 done < <(yq '.generates.tables[] | @json' "${config}")
 
-if [ ${#failed_tables[@]} -gt 0 ]; then
+if [ "${#failed_tables[@]}" -gt 0 ]; then
     echo "ERROR: failed for ${#failed_tables[@]} table(s):" >&2
     for table in "${!failed_tables[@]}"; do
         echo "  '${table}': ${failed_tables[${table}]}" >&2
