feat: checkpoint

diff --git a/src/bin/pgp-make-partitions b/src/bin/pgp-make-partitions
--- a/src/bin/pgp-make-partitions
+++ b/src/bin/pgp-make-partitions
@@ -100,6 +100,7 @@ function make_partitions() {
         DEFAULT_SKIP_OVERLAPPING=false \
         DEFAULT_IDEMPOTENT=false \
         DEFAULT_STORAGE_PARAMETERS=null \
+        DEFAULT_STORAGE_MODE="inherit" \
         DEFAULT_TIMEZONE="Etc/UTC" \
         DIRECTORY="."
 
@@ -117,13 +118,15 @@ function make_partitions() {
     GLOBAL_PARTITION_TABLESPACE="$(yq '.lifecycle.partition.tablespace // strenv(DEFAULT_TABLESPACE)' "${config}")"
     GLOBAL_INDEX_TABLESPACE="$(yq '.lifecycle.partition.index.tablespace // strenv(DEFAULT_TABLESPACE)' "${config}")"
 
-    GLOBAL_PARTITION_STORAGE_PARAMETERS="$(yq -o=json '.lifecycle.partition.storage_parameters // (strenv(DEFAULT_STORAGE_PARAMETERS) | fromjson)' "${config}")"
+    GLOBAL_PARTITION_STORAGE_MODE="$(yq '.lifecycle.partition.storage.mode // strenv(DEFAULT_STORAGE_MODE)' "${config}")"
+    GLOBAL_PARTITION_STORAGE_PARAMETERS="$(yq -o=json '.lifecycle.partition.storage.parameters // (strenv(DEFAULT_STORAGE_PARAMETERS) | fromjson)' "${config}")"
+
     GLOBAL_INDEX_STORAGE_PARAMETERS="$(yq -o=json '.lifecycle.partition.index.storage_parameters // (strenv(DEFAULT_STORAGE_PARAMETERS) | fromjson)' "${config}")"
 
     export GLOBAL_PARTITION_TABLESPACE GLOBAL_INDEX_TABLESPACE GLOBAL_PARTITION_SCHEMA \
            GLOBAL_PARTITION_NAME_TEMPLATE GLOBAL_PAST GLOBAL_FUTURE GLOBAL_INTERVAL GLOBAL_START_TIMESTAMP GLOBAL_RETENTION \
            GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE GLOBAL_SKIP_OVERLAPPING GLOBAL_PARTITION_STORAGE_PARAMETERS \
-           GLOBAL_INDEX_STORAGE_PARAMETERS GLOBAL_IDEMPOTENT
+           GLOBAL_PARTITION_STORAGE_MODE GLOBAL_INDEX_STORAGE_PARAMETERS GLOBAL_IDEMPOTENT
 
     directory="$(yq '.lifecycle.directory // strenv(DIRECTORY)' "${config}")"
     timezone="$(yq '.lifecycle.partition.timezone // strenv(DEFAULT_TIMEZONE)' "${config}")"
@@ -200,19 +203,25 @@ function make_partitions() {
 
         default_partition_name_template="$(yq '.partition.default.naming.template // strenv(GLOBAL_DEFAULT_PARTITION_NAME_TEMPLATE)' <<< "${table}")"
 
-        partition_storage_parameters="$(yq '.partition.storage_parameters // strenv(GLOBAL_PARTITION_STORAGE_PARAMETERS)' <<< "${table}")"
+        partition_storage_mode="$(yq '.partition.storage.mode // strenv(GLOBAL_PARTITION_STORAGE_MODE)' <<< "${table}")"
+        partition_storage_parameters="$(yq '.partition.storage.parameters // strenv(GLOBAL_PARTITION_STORAGE_PARAMETERS)' <<< "${table}")"
+
+        # index_storage_mode="$(yq '.partition.index.storage_mode // strenv(GLOBAL_INDEX_STORAGE_MODE)' <<< "${table}")"
         index_storage_parameters="$(yq '.partition.index_storage_parameters // strenv(GLOBAL_INDEX_STORAGE_PARAMETERS)' <<< "${table}")"
 
-        template_table="$(yq '.template_table' <<< "${table}")"
+        template_table="$(yq '.template' <<< "${table}")"
 
         output_filename="$(pgp-get-migration-filename -t "${output_file_template}" -d "${temp_migration_directory}" -m "${description}")"
 
         echo "INFO: Making partitions for ${table_schema}.${table_name}"
 
         partition_start_timestamp="$(yq '.partition.start_timestamp // strenv(GLOBAL_START_TIMESTAMP)' <<< "${table}")"
-        # TODO: Manage errors from psql commands and fail gracefully with helpful error messages.
+
         if [[ "${partition_start_timestamp}" == "NOW" ]]; then
-            partition_start_timestamp="$(
+
+            echo "INFO: Using current timestamp for partition start timestamp"
+
+            if !  partition_start_timestamp="$(
                 psql \
                     --tuples-only \
                     --no-align \
@@ -221,25 +230,16 @@ function make_partitions() {
                     --variable timezone="${timezone}" \
                     <<EOF
 SET TIMEZONE TO :'timezone';
+
 SELECT now();
 EOF
-            )"
-        elif [[ "${partition_start_timestamp}" == "TODAY" ]]; then
-        # TODO: Manage errors from psql commands and fail gracefully with helpful error messages.
-            partition_start_timestamp="$(
-                psql \
-                    --tuples-only \
-                    --no-align \
-                    --quiet \
-                    --variable "ON_ERROR_STOP=1" \
-                    --variable timezone="${timezone}" \
-                    <<EOF
-SET TIMEZONE TO :'timezone';
-SELECT date_trunc('day', now());
-EOF
-            )"
+            )"; then
+                echo "ERROR: Failed to get current timestamp" >&2
+                exit 1
+            fi
 
         elif [[ "${partition_start_timestamp}" == "LATEST_PARTITION" ]]; then
+
             echo "INFO: Using latest partition for partition start timestamp"
 
             if ! partition_start_timestamp="$(
@@ -250,7 +250,10 @@ EOF
                     --variable "ON_ERROR_STOP=1" \
                     --variable table_schema="${table_schema}" \
                     --variable table_name="${table_name}" \
+                    --variable timezone="${timezone}" \
                     <<EOF
+SET TIMEZONE TO :'timezone';
+
 SELECT upper_bound
   FROM pgpartium.get_latest_partition(
            p_table_schema => :'table_schema'
@@ -269,6 +272,7 @@ EOF
         fi
 
         if [[ "${template_table}" == "DEFAULT_PARTITION" ]]; then
+
             echo "INFO: Using default partition as template table"
 
             if ! result="$(
@@ -406,6 +410,7 @@ EOF
                  --variable partition_schema="${partition_schema}" \
                  --variable partition_tablespace="${partition_tablespace}" \
                  --variable index_tablespace="${index_tablespace}" \
+                 --variable partition_storage_mode="${partition_storage_mode}" \
                  --variable partition_storage_parameters="${partition_storage_parameters}" \
                  --variable index_storage_parameters="${index_storage_parameters}" \
                  --variable template_table_schema="${template_table_schema}" \
@@ -430,6 +435,7 @@ SELECT *
   , p_partition_schema=>:'partition_schema'
   , p_partition_tablespace=>NULLIF(:'partition_tablespace', 'null')
   , p_index_tablespace=>NULLIF(:'index_tablespace', 'null')
+  , p_partition_storage_mode=>:'partition_storage_mode'
   , p_partition_storage_parameters=>NULLIF(:'partition_storage_parameters', 'null')::jsonb
   , p_index_storage_parameters=>NULLIF(:'index_storage_parameters', 'null')::jsonb
   , p_template_table_schema=>NULLIF(:'template_table_schema', 'null')
